


# name: Update Databricks Notebooks

# on:
#   push:
#     branches:
#       - master

# jobs:
#   update-databricks-notebooks:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Install Python and dependencies
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.x'

#       - name: Install required Python modules
#         run: |
#           pip install GitPython requests

#       - name: Run Python script to update Databricks
#         run: |
#           python update_pyfile.py
#         env:
#           DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}





name: Upload to Databricks

on:
  push:
    branches:
      - master  # Change this to your repository's main branch name

jobs:
  upload_to_databricks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Choose your Python version

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli

      - name: Upload files to Databricks workspace
        run: |
          for file in $(find $GITHUB_WORKSPACE/testing -name '*.py'); do
            databricks workspace import --language PYTHON "$file" '/Repos/git_checking/testing_data/testing/$(basename $file)' --overwrite
          done
        env:
          DATABRICKS_HOST: 'https://adb-5219522611471112.12.azuredatabricks.net'  # Replace with your Databricks URL
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}  # Replace with your Databricks API token

